services:
  eureka-server:
    build:
      context: ../ticketflow-eureka-server
      dockerfile: dockerfile
    container_name: ticketflow-eureka-server
    ports:
      - "8761:8761"

  postgres:
    image: postgres:18-alpine
    container_name: ticketflow-user-db
    environment:
      POSTGRES_DB: TicketFlow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ticketflow-user-service
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/TicketFlow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: ${JWT_SECRET:ticketflow-dev-secret-key-change-me-in-production-2026}
      EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka
    ports:
      - "8081:8081"
    depends_on:
      eureka-server:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  postgres_data: